### ISSUE TITLE
conifer output not to specific readIDs

### ISSUE THREAD

**Issue by ellyyuyang** [Ivarz/Conifer#7]
Hello,

Thanks for developing this tool! I have recently come across it and thought it would help me to fine tune the accuracy of my Kraken2 results. I read in the readme file that it generates the confidence scores for each readID. However, in my conifer output file, I see the confidence score for each taxid/taxname, as opposed to readID. Is there anything I did wrong?

Thanks,
Elly

**Comment by Ivarz** [comment]
Dear Elly,

Sorry for delayed response. Conifer assigns confidence scores for each read by default. However, if you are using flag `-s`, then score summary per taxonomy will be reported instead. So you should probably remove `-s` flag from the command.

Hope this helps,
Ivars

**Comment by ellyyuyang** [comment]
Dear Ivars,

I see, got it! Thanks for your reply! 

Best,
Elly
